server:
  port: 8090

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create

#facebook:
#  client:
#    clientId: clientIdTest
#    clientSecret: clientSecret
#    accessTokenUri: https://grah.facebook.com/oauth/accsee_token
#    userAuthorizationUri: https://www.facebook.com.dialog.oauth?display=popup
#    tokeName: oauth_token
#    authenticationScheme: query
#    clientAuthenticationScheme: form
#    scope: email
#  resource:
#    userInfoUri: https://graph/facebook.com/me?fields=id,email,link

google:
  client:
    clientId: 301775148598-74a5r05tlg0qls28nfebdmbq6cpu0rfu.apps.googleusercontent.com
    clientSecret: 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
    accessTokenUri: https://accounts.google.com/o/oauth2/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
    scope: email, profile
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v2/userinfo

kakao:
  client:
    clientId: 3cb8cacbfc107cf82cf433b7eac6ea6d
    accessTokenUri: https://kauth.kakao.com/oauth/token
    userAuthorizationUri: https://kauth.kakao.com/oauth/authorize
  resource:
    userInfoUri: https://kapi.kakao.com/v1/user/me

#  h2:
#    console:
#      enabled: true
#      path: /console
#  devtools:
#    livereload:
#      enabled: true
#  thymeleaf:
#    cache: false
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 881218558153-ndr868i68rlofoo4l2gb488ksabi5q23.apps.googleusercontent.com
#            client-secret: kq6zIo0myJotHK5_0irhtYnW
#          facebook:
#            client-id: 465358593799840
#            client-secret: a37286e3dae00dcdce628f40dfe363f5
#custom:
#  oauth2:
#    kakao:
#      client-id: 1b8ff676ae01724ed77437f98d399543